config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/doctrine' => 'pages#doctrine'
  get '/donate' => 'pages#donate'
  get '/donate/index.html' => 'pages#donate'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def doctrine
  end

  def about
  end

  def contact
  end

  def donate
  end
end

app/controllers/sermons_controller.rb
class SermonsController < ApplicationController
    def index
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Word of Truth Baptist Church - Prescott Valley, AZ"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sermons_helper.rb
module SermonsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#d91d28">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#b91d47">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-92259981-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-92259981-2');
  </script>
<% end %>

app/views/layouts/_navigation.html.erb
<div class='black-navigation mb-4 mx-auto'>
    <%= link_to 'Doctrine', doctrine_path, class: '' %>
    <%= link_to 'Donate', donate_path, class: '' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'application/favicon' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= render('layouts/google_analytics') %>
  </head>

  <body>
    <div id="main-width" class="container mt-2">
      <div class='box-1'>
        <%= link_to image_tag('WOTBC-LOGO.svg', width: 500, class: 'my-4 mx-auto d-block'), root_path %>
      </div>
      
      <%= render('layouts/navigation') %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/doctrine.html.erb
<% provide(:title, "Doctrine") %>
<div class="white-box py-4 px-4">
  <h1>What We Believe</h1>
  <p>We believe salvation is a free gift, given to us by God at the moment you put your faith in the Lord Jesus Christ. A believer has eternal life and can never lose their salvation (once saved, always saved.)</p>
  <p>We believe that the unbeliever will spend an eternity of torture and torment in a literal, fiery hell.</p>
  <p>We believe that the King James Bible is the preserved Word of God for us in the English language and is without error. We are a "King James Bible only" church.</p>
  <p>We believe that Jesus Christ was God manifest in the flesh, born of a virgin, lived a sinless life, was crucified on a cross, was buried, and rose again from the dead after 3 days.</p>
  <p>We believe that the godhead consists of the Father, the Word (Jesus Christ), and the Holy Ghost and these three are one (the trinity.)</p>
  <p>We believe that a New Testament church should be independent, with Christ as its head, and not part of a denomination.</p>
  <p>We believe that a church, by definition is an assembly of believers and reject the teaching of a universal church.</p>
  <p>We reject the teaching of Calvinism on all five points.</p>
  <p>We believe that the rapture will happen after the tribulation, but before God pours out his wrath upon the earth.</p>
  <p>We believe that those who are saved ought to live a life pleasing to God in accordance to his laws and not "the way of the world."</p>
</div>

app/views/pages/donate.html.erb
<% provide(:title, "Donate") %>
<h3 class="text-center">Click any link below to donate to Faithful Word Baptist Church</h3>

<div class='d-flex justify-content-center my-4'>
    <%= link_to 'Donate 1', 'https://secure.processdonation.org/faithfulwordbaptist/Donation.aspx?donationrefid=HHE67HABD6335', class: 'red-btn h1 mx-auto', target: '_blank' %>
</div>
<div class='d-flex justify-content-center my-4'>
    <%= link_to 'Donate 2', 'https://secure.usaepay.com/pay/5nkt6j1jx5d4ccsgb/d0VrtDsp', class: 'red-btn h1 mx-auto', target: '_blank' %>
</div>

app/views/welcome/index.html.erb
<%= image_tag 'front-image.jpg', width: '100%' %>